<?php
/**
 * @file
 * Custom functions for Grid View Bootstrap.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\grid_view_bootstrap\GridViewBootstrap;

/**
 * Implements hook_help().
 */
function views_bootstrap_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.grid_view_bootstrap':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The <a href="https://www.drupal.org/project/grid_view_bootstrap">Grid View Bootstrap4 module</a> adds styles to Views to output the results of a view as several common <a href="http://getbootstrap.com/components/">Twitter Bootstrap</a> grid layout.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('<a href="/admin/structure/views/add">Create a view</a> using one of the following styles:') . '</p>';
      $output .= '<ul>';
      $output .= '<li>' . t('<a href="https://getbootstrap.com/docs/4.2/layout/grid/">Grid</a>') . '</li>';
      $output .= '<ul>';

      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function grid_view_bootstrap_theme() {
  return GridViewBootstrap::getThemeHooks();
}
